### ISSUE TITLE
MODBUS Exception Responses

### ISSUE THREAD

**Issue by unreal79** [ceremcem/modbus_lib#2]
According to _Modbus_Application_Protocol_V1_1b3.pdf_:

> Function Code Field: In a normal response, the server echoes the function code of the original request in the function code field of the response. All function codes have a most–significant bit (MSB) of 0 (their values are all below 80 hexadecimal). In an exception response, the server sets the MSB of the function code to 1. This makes the function code value in an exception response exactly 80 hexadecimal higher than the value would be for a normal response.

Currently `modbus_lib_send_error` does not comply to the Modbus standard. It is easily patchable:
```
        uint8_t res[MB_EXCEPTION_LENGTH] = {
            config->address, 
            g_modbus_lib_received_telegram[1] + 0x80,
            error_code
        };
```

**Comment by ceremcem** [comment]
Thanks for the report and the patch. I spent some time to understand how the `g_modbus_lib_received_telegram[1] **+ 0x80**` line sets the MSB but I failed to do so. Is there any reason for that line not to be `g_modbus_lib_received_telegram[1] | 0x80`?

**Comment by unreal79** [comment]
Sorry for the misleading ** part (I was trying to emphasize the `+0x80` inside code section, but failed). Edited.

I see no reason not to use `| 0x80` -- it's a tiny bit faster then addition.

**Comment by ceremcem** [comment]
Sorry for being unresponsive for a while. Would you like to create a PR for this fix to get credit?

**Comment by unreal79** [comment]
No, submit the commit yourself please.
